calendars:
  - name: "Dar-ul-uloom Raheemiya"
    description: "Timings for Jammu and Kashmir (Fiqah Hanafiya) copied from Meeqat-us-Salaat, Darul Uloom Raheemiyyah, Bandipora. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "raheemiya"
    timings: "raheemiya.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhr
      - key: asr
        label: Asr
      - key: maghrib
        label: Maghrib
      - key: isha
        label: Isha
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4
  - name: "Educational Trust Kashmir"
    description: "Timings for Jammu and Kashmir (Fiqah Jaffaria) copied from calendar of Educational Trust Kashmir. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "etk"
    timings: "etk.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhrain
      - key: maghrib
        label: Maghribain
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4

custom_config:
  - name: "Shia Ithna-Ashari, Leva Institute, Qum"
    key: shia
    fajr: 16
    isha: 14
    magrhib: 4
  - name: "Gulf Region"
    key: gulf
    fajr: 19.5
    ishaInterval: 90
  - name: "Union Organization Islamic de France"
    key: france
    fajr: 12
    isha: 12
  - name: "Spiritual Administration of Muslims of Russia"
    key: russia
    fajr: 16
    isha: 15
  - name: "Jabatan Kemajuan Islam Malaysia (JAKIM)"
    key: jakim
    fajr: 20
    isha: 18
  - name: "Tunisia"
    key: tunisia
    fajr: 18
    isha: 18
  - name: "Algeria"
    key: algeria
    fajr: 18
    isha: 17
  - name: "Kementerian Agama Republik Indonesia"
    key: kemenag
    fajr: 20
    isha: 18
  - name: "Morocco"
    fajr: 19
    isha: 17







