calendars:
  - name: "Dar-ul-uloom Raheemiya"
    description: "Timings for Jammu and Kashmir (Fiqah Hanafiya) copied from Meeqat-us-Salaat, Darul Uloom Raheemiyyah, Bandipora. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "raheemiya"
    timings: "raheemiya.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhr
      - key: asr
        label: Asr
      - key: maghrib
        label: Maghrib
      - key: isha
        label: Isha
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4
  - name: "Educational Trust Kashmir"
    description: "Timings for Jammu and Kashmir (Fiqah Jaffaria) copied from calendar of Educational Trust Kashmir. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "etk"
    timings: "etk.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhrain
      - key: maghrib
        label: Maghribain
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4
  - name: "Jamiat Ahle Hadees J&K"
    description: "Timings for Jammu and Kashmir copied from calendar of Jamiat Ahle Hadees J&K. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "ahlehadees"
    timings: "ahlehadees.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhr
      - key: asr
        label: Asr
      - key: maghrib
        label: Maghrib
      - key: isha
        label: Isha
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4

custom_config:
  - name: "Shia Ithna-Ashari, Leva Institute, Qum"
    key: shia
    parameters:
        fajrAngle: 16
        ishaAngle: 14
        maghribAngle: 4
    description: "When fasting, for the matter of Ahtiyaat it's recommended to stop eating 10 mins prior to Adhan e Fajr"
  - name: "Gulf Region"
    key: gulf
    parameters:
      fajrAngle: 19.5
      ishaInterval: 90
  - name: "Union Organization Islamic de France"
    key: france
    parameters:
      fajrAngle: 12
      ishaAngle: 12
  - name: "Spiritual Administration of Muslims of Russia"
    key: russia
    parameters:
      fajrAngle: 16
      ishaAngle: 15
  - name: "Jabatan Kemajuan Islam Malaysia (JAKIM)"
    key: jakim
    parameters:
      fajrAngle: 20
      ishaAngle: 18
  - name: "Tunisia"
    key: tunisia
    parameters:
      fajrAngle: 18
      ishaAngle: 18
  - name: "Algeria"
    key: algeria
    parameters:
      fajrAngle: 18
      ishaAngle: 17
  - name: "Kementerian Agama Republik Indonesia"
    key: kement
    parameters:
      fajrAngle: 20
      ishaAngle: 18
  - name: "Morocco"
    key: morocco
    parameters:
      fajrAngle: 19
      ishaAngle: 17

iftarkar_calendars:
  - name: "Soutul Awliya Trust, J&K"
    description: "Timings for Jammu and Kashmir copied from calendar published by Soutul Awliya Trust, J&K"
    key: "tsajk"
    timings: "tsajk.csv"
    start_date: "0203"





