calendars:
  - name: "Dar-ul-uloom Raheemiya"
    description: "Timings for Jammu and Kashmir (Fiqah Hanafiya) copied from Meeqat-us-Salaat, Darul Uloom Raheemiyyah, Bandipora. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "raheemiya"
    timings: "raheemiya.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhr
      - key: asr
        label: Asr
      - key: maghrib
        label: Maghrib
      - key: isha
        label: Isha
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4
  - name: "Educational Trust Kashmir"
    description: "Timings for Jammu and Kashmir (Fiqah Jaffaria) copied from calendar of Educational Trust Kashmir. Default timings are for Srinagar, use Offsets to calculate for other areas."
    key: "etk"
    timings: "etk.csv"
    items:
      - key: fajr
        label: Fajr
      - key: zuhr
        label: Zuhrain
      - key: maghrib
        label: Maghribain
    offsets:
      - name: Pulwama, Kulgam, Harmukh
        offset: -1
      - name: Islamabad, Tral, Kud
        offset: -2
      - name: Pahalgam
        offset: -3
      - name: Leh
        offset: -11
      - name: Baramulla, Tangmarg, Sopore
        offset: 1
      - name: Bandipora, Poonch
        offset: 2
      - name: Uri
        offset: 3
      - name: Teetwal, Karnah
        offset: 4




